# Generated by Django 3.1.1 on 2020-12-01 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mypages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RenameField(
            model_name='vocab',
            old_name='pinyin',
            new_name='p',
        ),
        migrations.RemoveField(
            model_name='vocab',
            name='author',
        ),
        migrations.RemoveField(
            model_name='vocab',
            name='id',
        ),
        migrations.AlterField(
            model_name='vocab',
            name='word',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='VocabularySets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='a', max_length=15)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mypages.userdatabase')),
            ],
        ),
        migrations.AddField(
            model_name='vocab',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mypages.vocabularysets'),
        ),
    ]
