# Generated by Django 3.1.1 on 2020-12-20 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypages', '0002_auto_20201201_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabularysets',
            name='title',
            field=models.CharField(default='', max_length=15),
        ),
    ]
