# Generated by Django 3.1.1 on 2020-12-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypages', '0004_auto_20201221_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabularysets',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
