# Generated by Django 3.1.1 on 2020-12-22 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypages', '0006_auto_20201222_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocab',
            name='word',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
