# Generated by Django 3.1.1 on 2020-12-23 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypages', '0007_auto_20201222_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocab',
            name='id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vocab',
            name='word',
            field=models.CharField(default=True, max_length=20, primary_key=True, serialize=False),
        ),
    ]
