# Generated by Django 3.1.1 on 2020-12-23 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypages', '0012_auto_20201223_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocab',
            name='word',
            field=models.CharField(max_length=20),
        ),
    ]
