# Generated by Django 3.1.1 on 2020-12-23 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypages', '0013_auto_20201223_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocab',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
