# Generated by Django 3.1.1 on 2021-02-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypages', '0016_auto_20210115_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocab',
            name='star',
            field=models.BooleanField(default=False),
        ),
    ]
